import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body className={`${inter.className} min-h-screen transition-all duration-300 bg-zinc-100 dark:bg-zinc-900`}>{children}</body>
        <Footer />
      </Providers>
    </html>
  );
}
